window.WISHLIST_META = {
  verifiedAt: '2026-09-08',
  location: 'Москва',
  priceMin: 300,
  priceMax: 5000,
  maxDeliveryDays: 3
};

window.WISHLIST_GIFTS = [
  {code:'xiaomi-driver',title:'Xiaomi Mijia Electric Precision Screwdriver 24-in-1',subtitle:'Электрическая прецизионная отвёртка в алюминиевом кейсе',price:3955,shop:'Яндекс Маркет',category:'tech',star:true,delivery:'Москва: послезавтра',why:'Инструмент, который выглядит как хороший industrial design, а не как ящик из гаража. Разбирать гаджеты, чинить мелочь и просто получать удовольствие от хорошо сделанного предмета.',buyUrl:'https://market.yandex.ru/card/elektricheskaya-otvertka-xiaomi-mijia-electric-screwdriver-nabor-otvertka-s-bitami-24v1-mjddlsd003qw/102309323739'},
  {code:'ugreen-cm899',title:'UGREEN CM899 MagSafe M.2 NVMe enclosure',subtitle:'Магнитный корпус для SSD, USB-C 10 Гбит/с',price:3587,shop:'Яндекс Маркет',category:'tech',star:true,delivery:'Москва: 9 сентября',why:'Редкий случай, когда аксессуар одновременно полезный, странно-умный и визуально аккуратный. SSD, который магнитится к айфону, — достаточно инженерного абсурда, чтобы мне понравиться.',buyUrl:'https://market.yandex.ru/card/vneshniy-korpus-boks-dlya-ssd-m2-2230-nvme-ugreen-magnetic-magsafe-dlya-iphone-10-gbps/4602164137'},
  {code:'moondrop-chu2',title:'Moondrop Chu II DSP USB-C',subtitle:'Проводные IEM-наушники со встроенным DSP',price:2968,shop:'Яндекс Маркет',category:'tech',star:true,delivery:'Москва: завтра / экспресс сегодня',why:'Недорогой вход в нормальный IEM-звук плюс Type-C и DSP. Не очередные безликие TWS, а маленькая аудиоштука, с которой интересно сравнивать звук.',buyUrl:'https://market.yandex.ru/card/provodnyye-vnutrikanalnyye-naushniki-moondrop-chu-2-dsp-black-type-c-s-dinamicheskim-drayverom/4382336139'},
  {code:'8bitdo-micro',title:'8BitDo Micro',subtitle:'Карманный Bluetooth-геймпад',price:2062,shop:'Ozon',category:'tech',delivery:'Москва: завтра',why:'Миниатюрный контроллер размером почти с брелок. Полезен и для игр, и как физический набор кнопок для экспериментов и макросов — игрушка с шансом внезапно стать инструментом.',buyUrl:'https://www.ozon.ru/product/geympad-8bitdo-micro-bluetooth-usb-kabel-dlya-nintendo-switch-windows-android-i-ios-1660529375/'},
  {code:'ugreen-w703',title:'UGREEN W703 MagSafe 15W',subtitle:'Минималистичная беспроводная зарядка',price:3390,shop:'Регард',category:'tech',delivery:'Москва: доставка сегодня',why:'Хороший desk object: минимум визуального шума, нормальный материал, MagSafe и никакой RGB-ёлки. Вещь из категории «не купил бы срочно сам, но приятно иметь».',buyUrl:'https://www.regard.ru/product/710426/besprovodnoe-zariadnoe-ustroistvo-ugreen-wireless-charger-with-magsafe-15w-white-w703'},
  {code:'ugreen-cd137',title:'UGREEN CD137 20W',subtitle:'Компактная USB-C зарядка',price:990,shop:'Регард',category:'tech',delivery:'Москва: доставка сегодня',why:'Маленькая полезная вещь без церемоний. Зарядок почему-то всегда либо не хватает, либо они лежат не там. Нормальный подарок в бюджете около тысячи.',buyUrl:'https://www.regard.ru/product/431970/setevoe-zariadnoe-ustroistvo-ugreen-cd137-black'},
  {code:'pico-w',title:'Raspberry Pi Pico W с ногами',subtitle:'Микроконтроллер с Wi-Fi',price:1350,shop:'Амперка',category:'diy',star:true,delivery:'Москва: СДЭК 1–2 дня',why:'Маленькая плата = право внезапно сделать ненужное, но прекрасное устройство. Идеально для прототипов, кнопок, датчиков, физических интерфейсов и «а что если…».',buyUrl:'https://amperka.ru/product/raspberry-pi-pico-w-with-headers'},
  {code:'mikronik',title:'Микроник',subtitle:'Набор для экспериментов с электроникой',price:1590,shop:'Амперка',category:'diy',delivery:'Москва: СДЭК 1–2 дня',why:'Формально набор образовательный. Фактически — коробка для взрослого человека, которому всё ещё нравится замыкать две штуки и смотреть, что загорится. Это комплимент.',buyUrl:'https://amperka.ru/product/mikronik'},
  {code:'nixie-clock',title:'Nixie Clock',subtitle:'DIY-часы в духе газоразрядных индикаторов',price:3990,shop:'Амперка',category:'diy',star:true,delivery:'Москва: СДЭК 1–2 дня',why:'Ретрофутуризм, электроника, сборка и объект на стол — сразу четыре попадания. Выглядит как проп из хорошей фантастики, но его можно реально собрать.',buyUrl:'https://amperka.ru/product/nixie-clock'},
  {code:'io-kit-basic',title:'IO.KIT Базовый',subtitle:'Модульный набор по схемотехнике',price:2740,shop:'Амперка',category:'diy',star:true,delivery:'Москва: СДЭК 1–2 дня',why:'Не просто «детский конструктор», а аккуратная модульная система, из которой можно быстро собирать физические прототипы. Продуктовый дизайнер внутри меня будет доволен.',buyUrl:'https://amperka.ru/product/io-kit-basic'},
  {code:'soldering',title:'«Паяльник в лапах: зверская пайка»',subtitle:'Полный стартовый набор для пайки',price:4990,shop:'Амперка',category:'diy',star:true,delivery:'Москва: СДЭК 1–2 дня',why:'Чемоданчик, где уже есть почти всё: паяльник, расходники, инструменты, компоненты и даже комикс. Подарок с высокой вероятностью породить ещё один проект, который я обязательно «быстро доделаю».',buyUrl:'https://amperka.ru/product/soldering-starter-kit'},
  {code:'cyberbug',title:'CyberBug',subtitle:'Набор для пайки ползучего кибержука',price:990,shop:'Амперка',category:'diy',delivery:'Москва: СДЭК 1–2 дня',why:'Киберпанковский жук, который после 37 точек пайки светится, жужжит и ползёт по столу. Бессмысленность применения компенсируется безупречностью концепции.',buyUrl:'https://amperka.ru/product/cyberbug-kit'},
  {code:'cybermetal',title:'CyberMetal',subtitle:'DIY-портативный металлоискатель',price:1140,shop:'Амперка',category:'diy',delivery:'Москва: СДЭК 1–2 дня',why:'Спаять собственный металлоискатель за тысячу рублей — уже достаточно хороший сюжет для вечера. А потом можно искать в офисе потерянные скрепки с серьёзным лицом.',buyUrl:'https://amperka.ru/product/cybermetal-kit'},
  {code:'cyberid',title:'CyberID',subtitle:'Светящийся сенсорный магнит на холодильник',price:440,shop:'Амперка',category:'diy',delivery:'Москва: СДЭК 1–2 дня',why:'Самый дешёвый способ подарить мне кибербезопасность холодильника. Девять точек пайки — и доступ к еде официально становится high-tech.',buyUrl:'https://amperka.ru/product/cyberid-kit'},
  {code:'cyberlight',title:'CyberLight',subtitle:'Набор для пайки RGB-фонарика',price:740,shop:'Амперка',category:'diy',delivery:'Москва: СДЭК 1–2 дня',why:'Маленький RGB-фонарик с ручной регулировкой цвета: одновременно пайка, свет и микро-объект. Вполне может закончить жизнь как странный реквизит для съёмки или тест света.',buyUrl:'https://amperka.ru/product/cyberlight-kit'},
  {code:'arduino-uno',title:'Arduino Uno R3',subtitle:'Оригинальная плата Arduino',price:4790,shop:'Амперка',category:'diy',delivery:'Москва: СДЭК 1–2 дня',why:'Классика физического прототипирования. Для человека, который одновременно дизайнер, программист и постоянно придумывает устройства, это не плата — это разрешение на очередную затею.',buyUrl:'https://amperka.ru/product/arduino-uno'},
  {code:'iskra-uno',title:'Iskra Uno',subtitle:'Российский аналог Arduino Uno',price:2050,shop:'Амперка',category:'diy',star:true,delivery:'Москва: СДЭК 1–2 дня',why:'Тот же форм-фактор для физических прототипов, но заметно дешевле оригинальной Uno. Практичный подарок человеку, который способен начать проект с фразы «да там всего одна кнопка и датчик».',buyUrl:'https://amperka.ru/product/iskra-uno'},
  {code:'buran-pad',title:'Коврик «Энергия—Буран» XL',subtitle:'Большой desk mat 90×40 см с чехлом',price:1990,shop:'Амперка',category:'diy',star:true,delivery:'Москва: СДЭК 1–2 дня',why:'Советская инженерная мегаломания, космос, большая рабочая поверхность и хороший повод сделать стол чуть менее корпоративным. Очень правильная степень ретрофутуризма.',buyUrl:'https://amperka.ru/product/mousepad-buran'},
  {code:'itten-color',title:'Иоханнес Иттен — «Искусство цвета»',subtitle:'Классика теории цвета',price:1850,shop:'Музей «Гараж»',category:'design',star:true,delivery:'Москва: в наличии; курьер ≈1 день',why:'Не декоративный альбом, а базовая дизайнерская книга, к которой реально можно возвращаться. Профессиональный подарок без ощущения «я купил дизайнеру что-то про дизайн».',buyUrl:'https://shop.garagemca.org/ru/books/design/the-art-of-color-4169.html'},
  {code:'tschichold',title:'Ян Чихольд — «Новая типографика»',subtitle:'Руководство для современного дизайнера',price:1290,shop:'Музей «Гараж»',category:'design',star:true,delivery:'Москва: в наличии; курьер ≈1 день',why:'Типографическая база, исторический документ и очень живая профессиональная книга. В отдел дизайна можно потом цитировать с видом человека, который всё это знал заранее.',buyUrl:'https://shop.garagemca.org/ru/books/design/3600.html'},
  {code:'munari',title:'Бруно Мунари — «Фантазия»',subtitle:'О творчестве, изобретательстве и воображении',price:1080,shop:'Музей «Гараж»',category:'design',delivery:'Москва: в наличии; курьер ≈1 день',why:'Книга не про «как стать креативным за 7 шагов», а про механику воображения от человека, который действительно умел придумывать. Хорошее топливо для идей.',buyUrl:'https://shop.garagemca.org/ru/books/non-fiction/45946.html'},
  {code:'papanek',title:'Виктор Папанек — «Дизайн для реального мира»',subtitle:'Классика ответственного дизайна',price:1380,shop:'Музей «Гараж»',category:'design',delivery:'Москва: в наличии; курьер ≈1 день',why:'Про дизайн как решение реальных проблем, а не украшательство. Особенно хорошо сочетается с моими попытками придумывать продукты, сервисы и физические устройства, а не только картинки.',buyUrl:'https://shop.garagemca.org/ru/books/design/design-for-the-real-world-4000.html'},
  {code:'universal-principles',title:'«Универсальные принципы дизайна»',subtitle:'Большой справочник по законам проектирования',price:4100,shop:'Музей «Гараж»',category:'design',star:true,delivery:'Москва: в наличии; курьер ≈1 день',why:'Книга-настольный инструмент: визуальное восприятие, интерфейсы, поведение, композиция, продуктовые решения. То, что можно листать не линейно, а по конкретной задаче.',buyUrl:'https://shop.garagemca.org/ru/books/design/general-design/1249.html'},
  {code:'chayka',title:'Кайл Чайка — «В поисках минимализма»',subtitle:'Минимализм в искусстве, архитектуре и музыке',price:1110,shop:'Музей «Гараж»',category:'design',delivery:'Москва: в наличии; курьер ≈1 день',why:'Не очередное «выкиньте 30 вещей», а культурный разбор минимализма. Полезно человеку, который любит чистые системы, но регулярно наполняет их новыми идеями до отказа.',buyUrl:'https://shop.garagemca.org/ru/books/art/history-and-theory/the-longing-for-less-living-with-minimalism-36732.html'},
  {code:'moscow-build',title:'«Москва на стройке. 1917–1941»',subtitle:'1200 страниц архитектуры и визуальной культуры',price:4300,shop:'Музей «Гараж»',category:'design',star:true,delivery:'Москва: в наличии; курьер ≈1 день',why:'Физически огромный каталог архитектуры, графики и инженерной эпохи — 1200 страниц визуального исследования. Подарок на стыке Москвы, дизайна, истории производства и любви к большим системам.',buyUrl:'https://shop.garagemca.org/ru/books/garage-publications/19171941-52133.html'}
];